
FROM node:22-alpine


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


FROM nginx:alpine


COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 3000


CMD ["nginx", "-g", "daemon off;"]